services:
  plexgifmaker:
    build:
      context: .  # This should be the root directory containing the 'PlexGifMaker' folder
      dockerfile: PlexGifMaker/Dockerfile
    image: plexgifmaker:latest
    ports:
      - "9000:80"
      - "443:443"
    volumes:
      - plexgifmaker_keys:/usr/shared/plexgifmaker_keys
      - devcerts:/usr/shared/devcerts
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=localhost
      - VALIDATION=http
      - SUBDOMAINS=www, #optional
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - /path/to/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

volumes:
  plexgifmaker_keys:
    name: plexgifmaker_keys
