services:
  plexgifmaker:
    build:
      context: .  # This should be the root directory containing the 'PlexGifMaker' folder
      dockerfile: PlexGifMaker/Dockerfile
    image: plexgifmaker:latest
    ports:
      - "9000:80"
      - "443:443"
    volumes:
      - plexgifmaker_keys:/usr/shared/plexgifmaker_keys
    restart: unless-stopped

volumes:
  plexgifmaker_keys:
    name: plexgifmaker_keys
