services:
  plexgifmaker:
    build:
      context: .
      dockerfile: PlexGifMaker/Dockerfile
    image: plexgifmaker:latest
    ports:
      - "9000:9000"
    volumes:
      - ${PLEXGIFMAKER_DATA_PATH:-./plexgifmaker_keys}:/usr/shared/plexgifmaker_keys
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+;http://+:9000
      - FFREPORT=file="/logs/ffmpeg-$(date +%Y%m%s).log"
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "localhost"
      - "--config"
      - "/home/ngrok/.config/ngrok/ngrok.yml"
    volumes:
      - ./ngrok.yml:/home/ngrok/.config/ngrok/ngrok.yml
    depends_on:
      - plexgifmaker