services:
  plexgifmaker:
    build:
      context: .  # This should be the root directory containing the 'PlexGifMaker' folder
      dockerfile: PlexGifMaker/Dockerfile
    image: plexgifmaker:latest
    ports:
      - "9000:80"
    volumes:
      - plexgifmaker_keys:/usr/shared/plexgifmaker_keys
      #- ./certs:/https
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+

volumes:
  plexgifmaker_keys:
    name: plexgifmaker_keys
